Algoritmo "Entrada e saida de dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aula 3
// Autor(a)    : Jonathan
// Data atual  : 10/01/2023
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   leia(nome)
   leia(nota)

Fimalgoritmo