Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Declaração de variaveis Aula 2
// Autor(a)    : Jonathan
// Data atual  : 10/01/2023
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro
   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo